stages:
  - notify
  - deploy

deploy_django_app:
  stage: deploy
  image: ubuntu:latest  # Ubuntu tasvirini ishlatish
  only:
    - main
  before_script:
    - apt-get update && apt-get install -y openssh-client  # Ubuntu/Debian uchun to'g'ri paket o'rnatish buyruqlari
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
    - mkdir -p ~/.ssh
    - echo "$SSH_SERVER_HOSTKEYS" > ~/.ssh/known_hosts
  script:
    - ssh $SSH_USER@$SSH_HOST -p $SSH_PORT "
        cd $DEPLOY_PATH &&
        git pull origin main &&
        docker compose up --build -d &&
        docker image prune -f &&
        echo 'Deploy jarayoni muvaffaqiyatli yakunlandi!'"


telegram_notifications:
  stage: notify
  image: ubuntu:latest
  script:
    - apt-get update && apt-get install -y curl
    - >
      if [[ -n "$CI_COMMIT_BRANCH" ]]; then
        BRANCH="$CI_COMMIT_BRANCH branch"
        MESSAGE_TEXT="A new push to $BRANCH: $CI_COMMIT_MESSAGE by $GITLAB_USER_EMAIL."
      elif [[ "$CI_MERGE_REQUEST_EVENT_TYPE" == "created" ]]; then
        MESSAGE_TEXT="Merge Request Created: $CI_MERGE_REQUEST_TITLE by $CI_MERGE_REQUEST_AUTHOR."
      elif [[ "$CI_MERGE_REQUEST_EVENT_TYPE" == "updated" ]]; then
        MESSAGE_TEXT="Merge Request Updated: $CI_MERGE_REQUEST_TITLE."
      elif [[ "$CI_MERGE_REQUEST_EVENT_TYPE" == "merged" ]]; then
        MESSAGE_TEXT="Merge Request Merged: $CI_MERGE_REQUEST_TITLE by $CI_MERGE_REQUEST_AUTHOR."
      else
        MESSAGE_TEXT="Merge Request Event: $CI_MERGE_REQUEST_TITLE."
      fi
    - >
      curl -X POST "https://api.telegram.org/bot$TOKEN/sendMessage" -d 
      "chat_id=$CHAT_ID&text='${MESSAGE_TEXT}'&disable_web_page_preview=true&disable_notification=false"
  only:
    - main
    - dev