version: '3.11'
services:
  web:
    build: .
    restart: always
    command: ${COMMAND:-python3 manage.py runserver 0.0.0.0:8000}
    volumes:
    - .:/code
    ports:
    - 8081:8000
    depends_on:
    - db
    - redis
  db:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_DB: django
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: '2309'
    volumes:
    - pg_data:/var/lib/postgresql/data
  redis:
    restart: always
    image: redis
volumes:
  pg_data: null
