version: '3.11'
services:
  web:
    build: .
    restart: always
    command: ${COMMAND:-poetry run python3 manage.py runserver 0.0.0.0:8000}
    volumes:
      - .:/code
    ports:
      - ${PORT:-8001}:8000
    depends_on:
      - db
      - redis
  db:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - pg_data:/var/lib/postgresql/data
  redis:
    restart: always
    image: redis
volumes:
  pg_data: null
