APPS = [
    "rest_framework",
    "corsheaders",
    "django_filters",
    "rosetta",
    "django_redis",
    "rest_framework_simplejwt",
    "crispy_forms",
    "crispy_tailwind",
    "import_export",
    "django_ckeditor_5",
    "polymorphic",
    "drf_spectacular",
    "core.http.HttpConfig",
    "core.apps.accounts.apps.AccountsConfig",
]
