FROM jscorptech/django:latest

ARG SCRIPT="entrypoint.sh"
ENV SCRIPT=$SCRIPT

WORKDIR /code

COPY ./ /code

RUN --mount=type=cache,target=/root/.cache/uv uv pip install -r requirements.txt
COPY ./resources/scripts/$SCRIPT /code/$SCRIPT

RUN chmod +x /code/resources/scripts/$SCRIPT

CMD sh /code/resources/scripts/$SCRIPT


